name: Trigger multi runs

on:
  workflow_dispatch:
    inputs:
      run_count:
        description: "Number of times to run the test"
        required: true
        type: number
        default: 1

jobs:
  generate-iteration-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - id: generate-matrix
        run: |
          matrix="["
          for (( i=1; i<=${{ github.event.inputs.run_count }}; i++ )); do
            matrix="$matrix $i,"
          done
          matrix="$matrix]"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "matrix is: " $matrix

  single_job:
    needs: generate-iteration-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        run_iteration: ${{ fromJSON(needs.generate-iteration-matrix.outputs.matrix) }}
    steps:
      - name: echo
        run: |
          echo "Running iteration ${{ matrix.run_iteration }}"
